### ISSUE TITLE
Cults of Tibia

### ISSUE THREAD

**Issue by kito2** [kito2/mtibia-bounties#2]
**Ravennous Hunger - Ab'dendriel (Barkless)**

Video: https://www.youtube.com/watch?v=5Kx86tLyFwg

- Leiden (1): ![image](https://user-images.githubusercontent.com/21250744/45041972-fda9ec00-b03f-11e8-92a2-69f41010a02a.png)
- Wine Cask (2): ![image](https://user-images.githubusercontent.com/21250744/45041984-04d0fa00-b040-11e8-8cec-a2715d4a2129.png)
- Liquor Spirit (3): ![image](https://user-images.githubusercontent.com/21250744/45042070-3b0e7980-b040-11e8-9e9d-51b5fc6a23c5.png)
- Place (4): 
![image](https://user-images.githubusercontent.com/21250744/45042127-609b8300-b040-11e8-9b20-6b279dcb1cbd.png)
- Wine Cask's location (5): 
![image](https://user-images.githubusercontent.com/21250744/45042148-6b561800-b040-11e8-887c-5cbb78e7e81d.png)
- Liquor Spirit (area spell) (6): 
![image](https://user-images.githubusercontent.com/21250744/45042278-b40dd100-b040-11e8-9157-e5eebff6cd3d.png)
- Ravennous Hunger (7): ![image](https://user-images.githubusercontent.com/21250744/45042662-9c831800-b041-11e8-9f25-93f2874a0583.png)
----------------------------------------------------------------------
- [ ] When you go into the place, Leiden appears (50% hp) but you can't damage him. If you damage him, he heals himself.
- [ ] There are summons. 2 Barkless Fanatic which respawn after 10 seconds from his dead. (They've high damage, I recommend to create new XML for these monsters).
- [ ] In order to damage them, you've to go to the north and then attack Wine Cask who invoke Liquor Spirit:
> 1 summon maximum and spawns after 25-30 hits.
> When these summons are damaged, they attack with an area spell whose damage is between 1,000 and 4,000 hitpoints. It's a damage which is used every 3-5 seconds and damage creatures too (not players).
> Liquor Spirit dissapear after 10 seconds from his invocation.
[ ] When Leiden die, appears Ravennous Hunger, and Liquor Spirits now heal this boss (now we have to go far from the Wine Casks).
- [ ] Ravennous Hunger is inmune death.
- [ ] Ravennous Hunger invokes 4 Mutated Bats.
----------------------------------------------------------------------

**Comment by kito2** [comment]
**The Souldespoiler**

Video de referencia: https://www.youtube.com/watch?v=mQulm58JCD4

- The Sinister Hermit (Yellow) (1): ![image](https://user-images.githubusercontent.com/21250744/45044380-554b5600-b046-11e8-9d24-77577ffe3c72.png)
- The Sinister Hermit (Blue) (2): ![image](https://user-images.githubusercontent.com/21250744/45044512-b4a96600-b046-11e8-9ece-cf951e4076fa.png)
- Inactive Geyser (3): ![image](https://user-images.githubusercontent.com/21250744/45044389-5ed4be00-b046-11e8-973d-04ee151f5e39.png)
- Vermin Swarm (4): ![image](https://user-images.githubusercontent.com/21250744/45044589-eae6e580-b046-11e8-9434-6757198a322f.png)
- Ejemplo de Geyser Activado (5): ![image](https://user-images.githubusercontent.com/21250744/45044650-17026680-b047-11e8-9459-4ab5bbceb26b.png)
- The Souldespoiler: ![image](https://user-images.githubusercontent.com/21250744/45044760-66e12d80-b047-11e8-9c0a-398544b87710.png)
- Feed Soul: ![image](https://user-images.githubusercontent.com/21250744/45044779-76607680-b047-11e8-9051-3f7052fd3a95.png)



- [ ] Al entrar aparece The Sinister Hermit (Yellow) el cual es invulnerable y varios Inactive Geysers.
- [ ] Solo uno de todos estos se activa y envia un mensaje de **SPLASH** (naranjo), este Geyser se activara por 10-15 segundos (y sale una animacion de cascada sobre este), y luego se activara otro.
- [ ] Hay que lurear al boss al Geyser activo (debe pararse encima) para que se transforme en el The Sinister Hermit (Blue).
- [ ] Cada transformacion (ya sea Yellow o Blue), el boss summonea Vermin Swarm x2.
- [ ] Al morir el The Sinister Hermit, aparece The Souldespoiler el cual es inmortal (resistencias al 99%):
> Luego de un tiempo (cada 120 segundos) comienza a convocar Feed Soul los cuales, cada uno reduce sus resistencias en un 30%. 
> Cuando hay 3 Feed Soul ya liberados, el boss tiene resistencias al 9% y es sencillo de matar.

**Comment by kito2** [comment]
**The Voidborn - Edron**

Video de referencia: https://www.youtube.com/watch?v=VN48yor6SWQ

- Security Golem: ![image](https://user-images.githubusercontent.com/21250744/45045078-52e9fb80-b048-11e8-801b-cd8cf47b463c.png)
- Containment Machine: ![image](https://user-images.githubusercontent.com/21250744/45045105-6006ea80-b048-11e8-81eb-7a874f825c3a.png)
- The Armored Voidborn: ![image](https://user-images.githubusercontent.com/21250744/45045114-685f2580-b048-11e8-8c49-a4d31b62847e.png)
- Ejemplo de sala: 
![image](https://user-images.githubusercontent.com/21250744/45045221-b116de80-b048-11e8-8d52-1c14ebc115fe.png)
- [ ] Containment Crystal transformado: 
![image](https://user-images.githubusercontent.com/21250744/45045726-48306600-b04a-11e8-88c3-5d6df89bda7f.png)
- Voidhshard: ![image](https://user-images.githubusercontent.com/21250744/45045855-baa14600-b04a-11e8-9c5b-6e118ddb1be5.png)

 

- [ ] Al entrar, el The Armored Voidborn (resistencias al 99%) estara trapeado entre cuatro muros de energia. 
- [ ] Se debe matar los Security Golems y el Containment Machine para liberar el muro de energia y luego asi poder matar al boss.
- [ ] Al matar el Containment Machine, este se transforma en Containment Crystal.
- [ ] Los Containment Crystal al atacarlos liberan un ataque en area (azul como se ve en la imagen) que le hace daño al boss y ademas summonean Voidshards (sin limite de cantidad, pero se summonea uno a la vez por ataque liberado con exito contra el boss).
- [ ] Los druidas deben usar Mass Healing, los demas pueden usar UH/IH Rune para que no mueran los Containment Crystals.
- [ ] Al morir el The Armored Voidborn, se transforma en The Unarmored Voidborn (sus resistencias son casi -500%, por lo que los daños hasta mas sencillos hacen hits de 2000). Este boss tiene muchisima vida, por lo cual estos daños tan grandes, apenas le reducen la vida.

**Comment by kito2** [comment]
**The Sandking**

Video de referencia: https://www.youtube.com/watch?v=QUC3MN_OLZE

- Sand Vortex: ![image](https://user-images.githubusercontent.com/21250744/45046059-664a9600-b04b-11e8-9b36-d3119094e52d.png)
- The Sandking: ![image](https://user-images.githubusercontent.com/21250744/45046071-6ea2d100-b04b-11e8-9e2b-42370aaa9fc4.png)
- Sand Brood: ![image](https://user-images.githubusercontent.com/21250744/45046079-76fb0c00-b04b-11e8-81ee-9774be48abc2.png)

**Stage 1: Esto sucede hasta que el boss llega al 50% de su HP**
- [ ] The Sandking aparece en la centro del cuarto. 
> Hay que atacarlo con todo lo posible, ya que luego de 12 segundos desaparece. 
> En este momento se convocan los Sand Vortex (x4, uno en cada esquina);
> y comienzan a aparecer los Sand Brood (x2, uno al centro-norte y otro al centro-sur del cuarto).
> Se deben matar 15 Sand Brood para que el The Sandking vuelva a aparecer.
- [ ] Los Sand Vortexes son inmortales, y reflejan todo daño que  se les realizado (si no existe target para devolver el daño, no lo hace, impotante por los fields).
- [ ] Si el The Sandking camina sobre el cuerpo de un Sand Brood o un Enraged Brood, se curara 7500 de HP.

**Stage 2: Al llegar al 50% del HP por Stage 1, el boss se triplica y vuelve a tener 80% de su HP**
> Momento preciso de la triplicacion: https://youtu.be/QUC3MN_OLZE?t=237
- [ ] The Sandking se triplica, y son tres bosses, pero al dañar a uno, se le reduce la vida a los tres, por lo cual da lo mismo cual se ataca.
- [ ] Aparecen continuamente Enraged Sand Brood.

**Stage 3: Al morir los en Stage 2, aparece el The Sandking de forma mas debil y lento que antes, y solo hay que matarlo**

**Comment by kito2** [comment]
**The False God - Mintwallin (Minotaur Cultists)**

- The False God: ![image](https://user-images.githubusercontent.com/21250744/45049600-80897180-b055-11e8-8359-49ddc74373c9.png)
- Minotaur Idol: ![image](https://user-images.githubusercontent.com/21250744/45049618-8a12d980-b055-11e8-8493-0fa07b67c218.png)
- Sphere of Wrath: ![image](https://user-images.githubusercontent.com/21250744/45049712-d231fc00-b055-11e8-958b-78d08a355e47.png)
------------------------------------------------------------
- [ ] Al entrar, a la izquierda de la room aparece The False God y se puede comenzar a hacer daño inmediatamente.
- [ ] Los Minotaur Idol cada 20 segundos comienzan a "librerarse", es decir dejan de ser estatuas y se transforman en una creatura que hace daño.
- [ ] Cada 15% que se le reduce al The False God de HP; se summonea una Sphere of Wrath (indestructible, lenta y hacen mucho daño). En total, cuando el boss tiene 40% de HP (o menos), deberian haber un maximo de 4 de estas esferas.

**Comment by kito2** [comment]
**Esence of Malice - Carlin (Graveyard)**

- Los pilares y los bosses (1): 
![image](https://user-images.githubusercontent.com/21250744/45050284-3c976c00-b057-11e8-85ff-c9aaffc73cb0.png)
- Pillar of ...: ![image](https://user-images.githubusercontent.com/21250744/45050468-c5160c80-b057-11e8-96b4-f9871bd3987f.png)
- Destroyed Pillar: ![image](https://user-images.githubusercontent.com/21250744/45050482-cd6e4780-b057-11e8-9840-e083c5161b16.png)
- Essence of Malice: ![image](https://user-images.githubusercontent.com/21250744/45050601-145c3d00-b058-11e8-88fa-942d3b06336c.png)

---------------------------------------
- [ ] Al entrar al room, existen 5 pilares, y 5 bosses segun se indica en la imagen (1). 
- [ ] Cada Pilar tiene habilidades especificas:
> Pillar of Healing and Mezlon The Defiler (heals the other Pillars)
> Pillar of Draining and Dorokoll The Mystic (drains mana)
> Pillar of Summoning and Eshtaba The Conjurer (summons Dread Minions)
> Pillar of Death and Malkhar Deathbringer (deals Death damage)
> Pillar of Protection and Eliz The Unyielding (?)
- [ ] Los bosses son invulnerables, hasta que se lleva a 1 HP el respectivo pilar que protegen, y ahi luego se puede dañar el boss correspondiente.
> Cuando el pilar llega a 1 de HP; el boss queda en 20% de HP (rojo) y este se puede mover.
> Cuando el pilar llega a 1 de HP, cambia su nombre por Destroyed Pilar.
- [ ] Los bosses pueden ser curados por players con Mass Healing o UH/IH Rune.
- [ ] Cuando los 5 pilares y 5 mini-bosses mueren, aparece Essence of Malice (inmune al death, pero debil al earth +30%).

**Comment by kito2** [comment]
**The Source of Corruption - Feyrist**

- The Remorseless Corruptor: ![image](https://user-images.githubusercontent.com/21250744/45051728-43c07900-b05b-11e8-9b2d-2b90527d947d.png)
- Zarcorix of Yalahar: ![image](https://user-images.githubusercontent.com/21250744/45051739-4ae78700-b05b-11e8-866a-5126e2d48421.png)
- Stolen Soul: ![image](https://user-images.githubusercontent.com/21250744/45051816-900bb900-b05b-11e8-9500-4f3cf74dd07b.png)
- Soul Reaper: ![image](https://user-images.githubusercontent.com/21250744/45051826-95690380-b05b-11e8-8c6a-9d9ee890d00c.png)
- Guilt (Item): ![image](https://user-images.githubusercontent.com/21250744/45051994-f7c20400-b05b-11e8-8077-4318b74d2f8d.png)
- The Corruptor of Souls: ![image](https://user-images.githubusercontent.com/21250744/45052148-58e9d780-b05c-11e8-827e-16ba4da73f72.png)
- The Source of Corruption: ![image](https://user-images.githubusercontent.com/21250744/45052228-9a7a8280-b05c-11e8-9b85-d73f1cb53f34.png)
------------------------------------------------------------------
- [ ] Existe una puerta en Feyrist la cual solo debe permitir acceder tras haber vencido satisfactoriamente a los bosses previos.
![image](https://user-images.githubusercontent.com/21250744/45051674-1f649c80-b05b-11e8-85dd-860d1fb6ff19.png)
- [ ] Se puede combatir maximo de 10 players.
- [ ] Al entrar existen dos bosses. The Remorseless Corruptor y Zarcorix of Yalahar. Ambos invulnerables.
- [ ] Zarcorix of Yalahar devuelve cualquier daño recibido aumentado en 3 veces.
- [ ] Existen dos pisos superiores, donde:
> Aparecen los Dark Souls, los cuales al morir se transforman en Guilt y estos deben ser arrojados por los players al piso inferior.
> Si los Dark Souls viven mas de 30 segundos, se transforman en Soul Reapers.
> Los Guilt se ocupan sobre The Remorseless Corruptor y aparece el mensaje de You have raised the guilt of the corruptor. Cuando se ocupan alrededor de 50 Guilts en total para transformalo en The Corruptor of Souls (el cual se puede dañar).
> Los players deben continuar utilizando los Guilts sobre The Corruptor of Souls, de lo contrario vuelve a su transformation anterior The Remorseless Corruptor, y se vuelve invulenrable una vez mas.
 - [ ] Una vez que muere el The Corruptor of Souls, el boss de Zarcorix of Yalahar desaparece y en cambio, aparece The Source of Corruption, el cual convoca constamente y mantiene solo 2 Soul Reapers.
